//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BinanceAcountViewer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("H:\\Git\\BinanceApi\\binance-connector-dotnet\\dataTest")]
        public string TestData {
            get {
                return ((string)(this["TestData"]));
            }
            set {
                this["TestData"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\ilayv\\AppData:\\GitHub\\binance\\binance-downloader\\binance_downloader\\down" +
            "loaded\\LTC")]
        public string DataBase {
            get {
                return ((string)(this["DataBase"]));
            }
            set {
                this["DataBase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LTC")]
        public string SelectedCurrency {
            get {
                return ((string)(this["SelectedCurrency"]));
            }
            set {
                this["SelectedCurrency"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.001")]
        public double Fee {
            get {
                return ((double)(this["Fee"]));
            }
            set {
                this["Fee"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\mGitHub\\MyGit\\keys.txt")]
        public string PathToFileWithKeys {
            get {
                return ((string)(this["PathToFileWithKeys"]));
            }
            set {
                this["PathToFileWithKeys"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\mGitHub\\MyGit\\tradingStateTrain.txt")]
        public string PathToTradingStateReal {
            get {
                return ((string)(this["PathToTradingStateReal"]));
            }
            set {
                this["PathToTradingStateReal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\mGitHub\\MyGit\\tradingStateTrain.txt")]
        public string PathToTradingStateTrain {
            get {
                return ((string)(this["PathToTradingStateTrain"]));
            }
            set {
                this["PathToTradingStateTrain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\mGitHub\\MyGit\\walletInfo.txt")]
        public string PathToWalletFile {
            get {
                return ((string)(this["PathToWalletFile"]));
            }
            set {
                this["PathToWalletFile"] = value;
            }
        }
    }
}
